### ISSUE TITLE
WorldEdit is partially broken

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TF-WorldEdit#15]
[17:41:04] [Server thread/WARN]: [WorldEdit]
    **********************************************
    ** This WorldEdit version does not fully support your version of Bukkit.
    **
    ** When working with blocks or undoing, chests will be empty, signs
    ** will be blank, and so on. There will be no support for entity
    ** and biome-related functions.
    **
    ** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
    **********************************************

**Comment by OxLemonxO** [comment]
close this, @ChargedCreeper
