### ISSUE TITLE
WorldEdit needs to be updated

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TF-WorldEdit#21]
As @adamvandyck said in the TFM issues:

```
In the logs I get this message:
[13:58:50] [Server thread/WARN]: [WorldEdit]

** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters

Like the message says, when copying and pasting things like chests and signs they go blank which needs to be fixed.
```

This is correct although the original issue was in the wrong repo.

**Comment by Commodore64x** [comment]
@ShadowArmadyl migrating all the custom TF files to the latest worldedit version will fix this. This is what I am currently working on.

**Comment by JeromSar** [comment]
@ShadowArmadyl Is this on a private server? If so, please recompile the latest TF-WorldEdit. @OxLemonxO recently added the MC 1.10 adapter: https://github.com/TotalFreedom/TF-WorldEdit/commit/e616d9014b222f68c118873688f0dd9422e4f29f

**Comment by ShadowArmadyl** [comment]
@JeromSar My server has now abandoned TF-WorldEdit. We are running the normal version of the plugin and it works with TFM flawlessly. Another private server will be required to preform these tests.

**Comment by JeromSar** [comment]
@ShadowArmadyl Normal versions of WorldEdit allow all OPs (players) to use blocked blocks. It is up to you to decide whether or not you want this functionality.
