### ISSUE TITLE
World Edit Update Needed

### ISSUE THREAD

**Issue by markbyrn** [TotalFreedom/TF-WorldEdit#22]
This is the latest update to World Edit 
https://t.co/nizQwpfxf6

Anyway to get it modified for TF as was done with the previous update?

**Comment by JeromSar** [comment]
I'm working on it. :)

**Comment by Commodore64x** [comment]
@JeromSar I have already made a new version of Tf Worldedit that is 100% compatible with AsyncWorldEdit. I will make a PR sometime soon.
