### ISSUE TITLE
Task not found in root project

### ISSUE THREAD

**Issue by InfamousYT** [TotalFreedom/TF-WorldEdit#27]
Hi there,

When I attempt to compile the newest version of TF-WorldEdit I get the following error:

[buildinfo] Properties file path was not found! (Relevant only for builds running on a CI Server)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupDecompWorkspace' not found in root project 'worldedit'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info                                                                                                                        or                                                                                                                     --debug                                                                                                                  option to get more log output.

BUILD FAILED

Total time: 3.8 secs.

I am using command: C:\Users\\****\Desktop\TF-WorldEdit-tfm50>gradlew clean setupDecompWorkspace

Thank you in advanced,

InfamousYT.

**Comment by InfamousYT** [comment]
Fixed.

Issue solved - closed.

**Comment by Hockeyfan360** [comment]
@InfamousYT Mind explaining how you fixed this issue? I've had the same problem as well.

**Comment by mgflames** [comment]
@Hockeyfan360 I simply just didn't clean, just used 'gradlew build' - still works fine.
