### ISSUE TITLE
TotalFreedomMod in TF World Edit

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TF-WorldEdit#8]
So I cloned the world edit from github.com/TotalFreedom/worldedit.git and there was errors when Im done cloning it in NetBeans. The imports from TotalFreedomMod does not exist in the dependencies.
http://imgur.com/ikIgVCp,OtOZ5Pl,hl0S8k4  (There is First,Second,Third Image) @JeromSar @StevenLawson Pleases help :crying_cat_face:

**Comment by JeromSar** [comment]
@looperXD Please don't spam issues, but use one and continue discussion on it. You don't need 3 different issues for the same problem.

Make sure you have the latest TotalFreedom jar attached as a dependency.

**Comment by looperXD** [comment]
Srry @JeromSar  1 More question how do I add it to the dependency?

**Comment by looperXD** [comment]
When I search in the quarry "me.StevenLawson", it showed up as no result

**Comment by JeromSar** [comment]
@looperXD Add the depdency to NetBeans to allow NetBeans to include it when compiling.

**Comment by looperXD** [comment]
@JeromSar I m a newbie when it comes to java development, it alternate way, or could you further explain it? Thanks a lot for helping me. :smile:

**Comment by JeromSar** [comment]
@looperXD It's quite hard to explain something like this in chat. Try googling for it. :)
